language: java
deploy:
  provider: releases
  api_key:
    secure: mlEoE2YSrzj08LKU7e2cFrywCX0lObhtzHLzfB6o8Um4Olt/mlLpBXzvPxtbtV96E9Wsr91HReeTCiWnp/T+zUl7xhEfc6A9tOP9eT7byddgvnmoTHiu2PCeMs29aal5slCHLitxT40BXDQZWvQZhR/lP+1XSkS5GgfRWTYgyZ1uveHkReYiykmCG3K2aEn1sQSD8KC+Xy/JegSxncuOKzX9Xq56S/OcMefxPC4QuA/hUvsNEmok3cN3FwXIywgC5F+vzq6EFeLcCBNiwfy3xmN6l98b9oCNcDudRu+uKdunuY/WB1kyFwR8T/vWzSQWvRDne3Wshzq8jMSIX50SLJ2B6S+M3u5OZdtVSqFXVm+VY+lnM4DP4ao9k0ra4EdiVM7y1a/MpNqtZcXraLWrosPGhQY7inLDtUfLAQqkyPbjC3OGUsjdxYxUPuKydWcj/gkHMAv29MsUmBmy7Vy1XlPCjOPncExiBS+RJnq6I9+loMiwk3yEa7+86R4ubilKeHfOWkl0H2j6DyLJZ+pgWZ+Dz6XH8UQrEV1wovzVMuD+ksYi4eloobowdlakxG1fJEcX7wvKIcXxgjKb0LX6YMXJD2DBGqZIFMa9MFbSuoWFqyAebQRf2czk1JoXiT0mYna5GZamhis3JOVC2iN6Z90q8ysZ12NchMLSNbdxBhw=
  file: 
    - distribution/target/spl-1.0-bin.zip
    - distribution/target/spl-1.0-bin.tar.gz
  on:
    repo: envirover/SPLGroundControl
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: envirover
  local_dir: distribution/target
  upload-dir: spl
  region: us-west-2
  acl: public_read
  skip_cleanup: true
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: envirover
  local_dir: conf
  upload-dir: spl
  region: us-west-2
  acl: public_read
  skip_cleanup: true
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: envirover
  local_dir: aws
  upload-dir: spl
  region: us-west-2
  acl: public_read
  skip_cleanup: true