language: java
deploy:
  provider: s3
  access_key_id: AKIAJSWPG445RFXCOVSQ
  secret_access_key:
    secure: i0Yw6UeX9EUVrP0uCnHlA2RPWxRDev/GNycG+lPcJZUpTid0qhBLHOawPRx9ixfxfkOlgB+j35kWiu7E1fDHMgQFQse4gwBlLqBEteyD+a+CvhkNNUD0QjhftkQBpuhLHY8EQzkbjejgu3CJ5gG1gQlC+at+bVJBy5mZZ4W7xWbh1Exj2zmtsJJoWrzl9n9QZLlCaA8JzuqPVXuygg8Qd6rnp2DkfKZwpweTDsnlR+fszxbnpzGQyfDhKsd3N1sulxFI7C8QkI4rWCcJrrneakLobYPC0NLZg2RMIFunGWsJjjFqlFR7FQ2NJzaXTZdlkwabR5gzpKAnfWVA/DY5/H8LHkGYpvo8HMiFdEN0c2uh3QBRamejjuGPlS0Ppe1vpcL8PwzVG96ZtqCjcyOebKbAZ0FT5FKSg5hpNJqCO62UikqVOTJ5ivnBPzADnBVuH2mejIAjr2NKLBrqmff+VR3WbcD9nI6RuPj/aCYU4Mu1USYsyrkKatX2Z5lRSHd4D+X3Slp7NkiNGsEm4F3ZKopOVqYcIWNSr+OFoMKYLCFUpp3t1FCDC3VuK6Y224S+drJTubXd1gA3eaomIBJJVYu7LSw6ZSWIJKDRcrsGydmsHiCtvF7Oneq+nCYw/Q8efyTOGZCUwFVqf8lHZhkWgUeSIWEZ9IszRarFG+tx4bc=
  bucket: envirover
